#ifndef __ARK_STRINGS_SYSTEM_H__
#define __ARK_STRINGS_SYSTEM_H__

/*
Project:	Arkanoid

Programmer:	Jacek "TeMPOraL" Zlydach	[temporal@poczta.fm]

Created: 11.02.2004
Last Revised:	19.04.2004

Implementation File: None

Notes:
	
*/

/*
	This file contains #defines for strings in Arkanoid`s System String TBL
*/
#define STRING_SYS_GAMENAME 0
#define STRING_SYS_VIDEO_MODE_NOT_SUPPORTED 1
#define STRING_SYS_PROGRAM_WILL_NOW_CLOSE 2
#define STRING_SYS_FAILED_CREATING_WINDOW 3
#define STRING_SYS_FAILED_AQUIRING_DC 4
#define STRING_SYS_FAILED_CHOOSING_PIXELFORMAT 5
#define STRING_SYS_FAILED_SETTING_PIXELFORMAT 6
#define STRING_SYS_FAILED_CREATING_RC 7
#define STRING_SYS_FAILED_ACTIVATING_RC 8
#define STRING_SYS_ERROR_INITIALIZING_OPENGL 9
#define STRING_SYS_ERROR_INVALID_FMOD_VERSION 10
#define STRING_SYS_FAILED_INITIALIZING_FSOUND 11
#define STRING_SYS_ERROR_CREATING_DI8_INTERFACE 12
#define STRING_SYS_ERROR_INITIALIZING_KEYBOARD 13
#define STRING_SYS_ERROR_INITIALIZING_MOUSE 14
#define STRING_SYS_ERROR_HI_RES_TIMER_NOT_AVAIBLE 15
#define STRING_SYS_UNABLE_TO_LOAD_IMAGE 16
#define STRING_SYS_UNABLE_TO_LOAD_SOUND 17


#endif //__ARK_STRINGS_SYSTEM_H__